
###
POST http://localhost:8080/api/company/add
Content-Type: application/json


{
  "name": "Abbott Laboratories",
  "sector": "Health Care",
  "symbol": "ABT",
  "internshipList": [
    {
      "role": "Web developer",
      "company": "Abbott Laboratories",
      "location": "Casa",
      "duration": 17,
      "url": "https://github.com/quanyang/security-internships"
    },
    {
      "role": "Security Engineer Intern",
      "company": "Abbott Laboratories",
      "location": "San Francisco",
      "duration": 9,
      "url": "https://core.infosecconnect.com/amybadydyrIFSC/"
    }
  ]
}

